---
- name: "Create user"
  sudo: yes
  action: user name={{ piwik.user }} createhome=true shell=/bin/bash
  tags: main

- name: "Create log dir"
  file: state=directory dest=/home/{{ piwik.user }}/{{ item }} mode=0777 owner={{ piwik.user }}
  tags: main
  sudo: yes
  with_items:
    - logs

# Install Piwik
- include: piwik.yml tags=piwik