---
- include: dependencies_deb.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- include: dependencies_rpm.yml
  when: ansible_distribution in [ 'CentOS', 'RedHat', 'Fedora' ]

- include: db.yml

# Fetch latest release
- name: "Fetch latest Piwik release"
  sudo: yes
  action: get_url url={{ piwik.settings.url }}/{{ piwik.settings.file }} dest={{ piwik.settings.locations.tmp }} mode=0440 owner=root group=root
  tags: piwik

# Create Piwik destination folder
- name: "Create Piwik destination folder"
  sudo: yes
  action: file path={{ piwik.settings.locations.install }} owner={{ piwik.user }} group={{ piwik.user }} mode=0755 state=directory
  tags: piwik

# Extract package
- name: "Extract Piwik zipfile"
  sudo: yes
  action: shell unzip -u {{ piwik.settings.locations.tmp }}/{{ piwik.settings.file }} -d {{ piwik.settings.locations.install }} creates={{ piwik.settings.locations.dest }}
  tags: piwik

# Create Piwik temp folders
- name: "Create Piwik temp folders"
  sudo: yes
  action: file path={{ piwik.settings.locations.dest }}/{{ item }} owner={{ piwik.user }} group={{ piwik.user }} mode=0755 state=directory
  with_items: piwik.settings.web_writable_dirs
  tags: piwik

- include: nginx.yml

- include: geoip.yml