---
- name: "Restart Webserver"
  sudo: yes
  action: service name={{ piwik.webserver.service }} state=restarted

- name: "Reload Webserver"
  sudo: yes
  action: service name={{ piwik.webserver.service }} state=reloaded

- name: "Start Webserver, if not running"
  sudo: yes
  action: service name={{ piwik.webserver.service }} state=started

- name: "Stop Webserver, if running"
  sudo: yes
  action: service name={{ piwik.webserver.service }} state=stopped

- name: "Restart PHP"
  sudo: yes
  service: name=php5-fpm state=restarted